---
title: "compare_outlier"
author: "Frenk C.J. van Mil"
date: "4/12/2020"
output: pdf_document
---

```{r, result='hide', echo=FALSE, include=FALSE}
source('statistics.R')
```

```{r, results='hide', echo=FALSE, include=FALSE}
transformations <- list(
  c(13, log10_transform)
)
dbs_res <- readdbs('selected_dev_parsed', 'selected_dev_parsed_code', transformations=transformations, outlier_quantile = NULL)

data_og1 <- dbs_res$db1
data_cmp1 <- dbs_res$db2

dfs1 <- list(data_og1, data_cmp1)
dfnames1 = c('original1', 'code1')
rm(dbs_res)
```

```{r}
ggplot_line_ordered(data_og1, data_cmp1)
```

```{r, results='hide', echo=FALSE, include=FALSE}
transformations <- list(
  c(13, log10_transform)
)
dbs_res <- readdbs('selected_dev_parsed', 'selected_dev_parsed_code', transformations=transformations)

data_og2 <- dbs_res$db1
data_cmp2 <- dbs_res$db2

dfs2 <- list(data_og2, data_cmp2)
dfnames2 = c('original2', 'code2')
rm(dbs_res)
```

```{r}
ggplot_line_ordered(data_og2, data_cmp2)
```

```{r}
gt <- get_ground_truth()
```

```{r}
for (i in 2:6) {
  plot(sort(gt[,i]), main=colnames(gt)[[i]])
  print(mean(gt[,i]))
}
```
```{r}
for (i in 2:length(data_og2)) {
  current_mean <- mean(data_og2[,i])
  gt_mean <- mean(gt[,get_trait_id(trait_name=colnames(data_og2)[[i]],index=TRUE)])
  data_og2[,i] <- data_og2[,i] + (gt_mean - current_mean)
  
  plot(sort(data_og2[,i]), main=colnames(data_og2)[[i]])
  print(paste(mean(data_og2[,i]),colnames(data_og2)[[i]]))
}
```

```{r}
inspect_gt_non_zero(data_og1, data_cmp1, dfnames=dfnames, gt=gt)
```

```{r}
inspect_gt_non_zero(data_og2, data_cmp2, dfnames=dfnames, gt=gt)
```


```{r, results='hide', echo=FALSE, include=FALSE}
transformations <- list(
  c(13, log10_transform)
)
dbs_res <- readdbs('selected_dev_parsed', 'selected_dev_parsed_code', transformations=transformations)

data_og3 <- dbs_res$db1
data_cmp3 <- dbs_res$db2

dfs3 <- list(data_og3, data_cmp3)
dfnames3 = c('original3', 'code3')
rm(dbs_res)
```

```{r}
for (i in 2:length(data_og3)) {
  current_mean <- mean(data_og3[,i])
  gt_mean <- mean(gt[,get_trait_id(trait_name=colnames(data_og3)[[i]],index=TRUE)])
  data_og3[,i] <- data_og3[,i] + (gt_mean - current_mean)
  data_og3[,i] <- ifelse(data_og3[,i] > 1, 1, data_og3[,i])
  data_og3[,i] <- ifelse(data_og3[,i] < 0, 0, data_og3[,i])
  
  plot(sort(data_og3[,i]), main=colnames(data_og3)[[i]])
  print(paste(mean(data_og3[,i]),colnames(data_og3)[[i]]))
}
```

```{r, results='hide', echo=FALSE, include=FALSE}
dbs_res <- readdbs('selected_dev_parsed', 'selected_dev_parsed_code', transformations=transformations)

data_og4 <- dbs_res$db1
data_cmp4 <- dbs_res$db2

dfs4 <- list(data_og4, data_cmp4)
dfnames4 = c('original4', 'code4')
rm(dbs_res)
```

```{r}
for (i in 2:length(data_og4)) {
  current_mean <- mean(data_og4[,i])
  gt_mean <- 0.5
  data_og4[,i] <- data_og4[,i] + (gt_mean - current_mean)
  data_og4[,i] <- ifelse(data_og4[,i] > 1, 1, data_og4[,i])
  data_og4[,i] <- ifelse(data_og4[,i] < 0, 0, data_og4[,i])
  
  plot(sort(data_og4[,i]), main=colnames(data_og4)[[i]])
  print(paste(mean(data_og4[,i]),colnames(data_og4)[[i]]))
}
```

```{r}
ggplot_line_ordered(data_og3, data_cmp3)
```

```{r}
inspect_gt_non_zero(data_og1, data_cmp1, dfnames=dfnames, gt=gt)
```

```{r}
inspect_gt_non_zero(data_og3, data_cmp3, dfnames=dfnames, gt=gt)
```

```{r}
inspect_gt_non_zero(data_og4, data_cmp4, dfnames=dfnames, gt=gt)
```

```{r}
whos_better(data_og, data_og3, gt, dfnames=c('normal', 'fixed'))
```

```{r}
whos_better(data_og, data_og4, gt, dfnames=c('normal', 'fixed'))
```

```{r}
measure_plot(dfs=list(data_og, data_og3, data_og4), gt=gt, dfnames=c('original', 'fixed', '0.5'), func=RMSE)
measure_plot(dfs=list(data_og, data_og3, data_og4), gt=gt, dfnames=c('original', 'fixed', '0.5'), func=MAE) 
```


