---
title: "Research Question 3"
author: "Frenk C.J. van Mil"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r, result='hide', echo=FALSE, include=FALSE}
source('statistics.R')
knitr::opts_chunk$set(comment = NA)
knitr::opts_chunk$set(results = 'asis')
```

### Read in data
```{r, results='hide', echo=FALSE, include=FALSE}
transformations <- list(
  c(13, log10_transform)
)
dbs_res0 <- readdbs('selected_dev_parsed', 'selected_dev_parsed', transformations=transformations, raw=c(TRUE,FALSE))
dbs_res1 <- readdbs('selected_dev_parsed_liwc_nofix', 'selected_dev_parsed_liwc_agree', transformations = transformations)
dbs_res2 <- readdbs('selected_dev_parsed_liwc_full', 'selected_dev_parsed_liwc_transf', transformations = transformations)

data <- dbs_res0$db1        # Best transformations on LIWC.
data_PI <- dbs_res0$db2     # Best transformations and percentile scores PI.
data_nofix <- dbs_res1$db1  # No fixes applied. Original methods.
data_agree <- dbs_res1$db2  # Transformation on 'you' for A and 'Exclam' for N.
data_full <- dbs_res2$db1   # All outlying scores reduced.
data_transf <- dbs_res2$db2 # Transformations on 'you', and 'cause' for A, 'Exclam' for N.

data_PI[,2:6] <- round(data_PI[,2:6] / 100, 2)
data_PI[,7:16] <- data[,7:16]

rm(dbs_res0)
rm(dbs_res1)
rm(dbs_res2)

data_nofix <- data_nofix[(data_nofix$id %in% data$id),]
data_agree <- data_agree[(data_agree$id %in% data_nofix$id),]
data <- data[(data$id %in% data_nofix$id),]
data_PI <- data_PI[(data_PI$id %in% data_nofix$id),]
data_full <- data_full[(data_full$id %in% data_nofix$id),]
data_transf <- data_transf[(data_transf$id %in% data_nofix$id),]

dfs <- list(data_nofix, data_agree, data_full, data_transf, data, data_PI)
dfnames <- list('[nofix]', '<agree]', '<full]', '<transf]', '<best]', '<PI]')
colors <- c(color$c1,color$c2,color$c3,color$c4,color$c5, color$c6)
```
First we read in the data and save this to four different datasets: data (comments with >3000 words), data_1200 (comments truncated to 1200 words), data_600 (comments truncated to 6000 words), and data_100 (comments truncated to 100 words).

### Compare density plots
```{r}
cols <- colnames(data)
for (i in 2:length(cols)) {
  column <- cols[i]
  densitynofix <- density(data_nofix[,i])
  densityagree <- density(data_agree[,i])
  densitynormal <- density(data[,i])
  densityPI <- density(data_PI[,i])
  densityfull <- density(data_full[,i])
  densitytransf <- density(data_transf[,i])
  maximum <- max(max(max(max(max(max(densityfull[['y']]),max(densityagree[['y']])),densitynormal[['y']]),densitytransf[['y']]),densitynofix[['y']]),densityPI[['y']])
  plot(densitynofix, main=paste('Density plot',column), col=colors[[1]], ylim=c(0,maximum))
  lines(densityagree, col=colors[[2]])
  lines(densitynormal, col=colors[[3]])
  lines(densityfull, col=colors[[4]])
  lines(densitytransf, col=colors[[5]])
  lines(densityPI, col=colors[[6]])
  legend(x="topright", y=0.92, legend=dfnames, col=colors, pch=rep('-',length(dfnames)), lwd=10)
}
```

```{r}
get_ylim <- function(dfs, column) {
  ylim_lower <- 1
  ylim_upper <- 0
  for (df in dfs) {
    lowerq <- quantile(df[,column])[2]
    upperq <- quantile(df[,column])[4]
    iqr <- upperq - lowerq
    ylim_lower <- min(lowerq - (iqr*1.5),ylim_lower)
    ylim_upper <- max((iqr*1.5) + upperq,ylim_upper)
  }
  return(c(ylim_lower,ylim_upper))
}
```

```{r}
outline = FALSE
for (i in 6:length(cols)) {
  column <- cols[i]

  boxwex <- 0.6
  at_pos <- c(0.1, 0.45, 0.8, 1.15, 1.5, 1.85)
  boxplot(data_nofix[,i], xlim=c(0,2), ylim=get_ylim(dfs,i), at=at_pos[1], main=paste('Boxplots',column), col=colors[[1]], outline=outline, boxwex=boxwex)
  boxplot(data_agree[,i], add=TRUE, at=at_pos[2], col=colors[[2]], outline=outline, boxwex=boxwex)
  boxplot(data_full[,i], add=TRUE, at=at_pos[3], col=colors[[3]], outline=outline, boxwex=boxwex)
  boxplot(data_transf[,i], add=TRUE, at=at_pos[4], col=colors[[4]], outline=outline, boxwex=boxwex)
  boxplot(data[,i], add=TRUE, at=at_pos[5], col=colors[[5]], outline=outline, boxwex=boxwex)
  boxplot(data_PI[,i], add=TRUE, at=at_pos[6], col=colors[[6]], outline=outline, boxwex=boxwex)
  axis(1, 1:length(dfnames), labels=dfnames, at=at_pos)
}
```

### Normality with QQ-Plots
```{r}
DISABLE_QQ_PLOTS = TRUE


draw_qqplots_rq3 <- function(dfs, dfnames) {
  for (i in 1:length(dfs)) {
    df <- dfs[[i]]
    for (column in 2:length(df)) {
      qqnorm(df[,column], pch=1, frame=FALSE, main = paste0(dfnames[[i]],": ",colnames(df)[[column]]))
      qqline(df[,column], col="steelblue", lwd=2)
    }
  }
}
if (!DISABLE_QQ_PLOTS) {
  draw_qqplots_rq3(dfs, dfnames)
} else {
  print('QQ-plots disabled for speed.')
}
```

```{r}
# Textually describe the dataframes.
summarize_df_rq3 <- function(dfs, dfnames=c(NULL,NULL,NULL,NULL)) {
  
  summ_df <- data.frame(Df=character(),
                        Column=character(), 
                        Min=double(), 
                        '1st Qu.'=double(), 
                        Median=double(), 
                        Mean=double(), 
                        '3rd Qu.'=double(), 
                        Max=double(), 
                        stringsAsFactors = FALSE)
  
  summarize_col <- function(in_df, i, res_df, dfname) {
    dfname <- ifelse(is.null(dfname), deparse(substitute(in_df)), dfname)
    res <- summary(in_df[,i])
    res_df[nrow(res_df)+1, ] <- c(dfname,
                                  colnames(in_df)[i],
                                  round(res['Min.'],2),
                                  round(res['1st Qu.'],2), 
                                  round(res['Median'],2),
                                  round(res['Mean'],2),
                                  round(res['3rd Qu.'],2),
                                  round(res['Max.'],2))
    res_df
  }
  for (i in 2:length(colnames(dfs[[1]]))) {
    for (idf in 1:length(dfs)) {
      summ_df <- summarize_col(dfs[[idf]], i, summ_df, dfnames[idf])
    }
  }
  summ_df
}

## Summarize data
summarize_df_rq3(dfs, dfnames=dfnames)
```

# Ground-truth inspection
```{r}
gt <- get_ground_truth()
```

```{r}
# Get the squared-error.
SE(data_agree, gt)
```
```{r}
# Get the Mean-quared-error.
MSE(data_agree, gt)
```

```{r}
# Get the Root-mean-squared-error, which is NRMSE (normalized) at the same time due to 0-1 scaling!
RMSE(data_agree, gt)
```

```{r}
# Get the Mean-Absolute-Error.
MAE(data_agree, gt)
```

```{r}
# Check the RMSE on each personality trait.
measure_plot(dfs=dfs, dfnames=dfnames, gt=gt, func=RMSE)
```

```{r}
measure_plot(dfs=list(data_nofix[,c(1,7:16)], data[,c(1,7:16)]), dfnames=list('No transformations', 'Transformations'), gt=gt, func=MAE, size_in_legend = FALSE, truncate_columns = TRUE, main="MAE scores with and without transformations on LIWC categories")
```

```{r}
# Check the MAE on each personality trait.
measure_plot(dfs=dfs, dfnames=dfnames, gt=gt, func=MAE)
```

```{r}
# for (df in dfs) {
#   print(Correlation(df, gt), method="pearson")
# }
```

```{r}
scatter <- function(df, gt, default_scaling=TRUE) {
  for (i in 2:16) {
    trait_idx <- (i - 2) %% 5 + 1
    trait <- traits[[trait_idx]]
    df.m <- merge(df, gt, by="id")
    p <- ggplot() + 
      geom_point(data=df.m, aes(x=df.m[,i], y=df.m[,(trait_idx+16)])) +
      geom_abline(intercept = 0, slope = 1) +
      ggtitle(paste(colnames(df.m)[i], 'vs', colnames(df.m)[trait_idx+16])) +
      xlab(colnames(df.m)[i]) + ylab(colnames(df.m)[trait_idx+16])
    if (default_scaling) {
      p <- p + scale_x_continuous(limits=c(0, 1), breaks=unlist(lapply(c(1:10), FUN=function(x) x/10))) +
        scale_y_continuous(limits=c(0, 1), breaks=unlist(lapply(c(1:10), FUN=function(x) x/10)))
    }
    print(p)
  }
}
scatter(data_nofix, gt)
```

```{r}
scatter(data, gt)
```


```{r}
centralize <- function(df, columns, rounding=2) {
  df.mean <- data.frame(df[,1:tail(columns,1)])
  df.mean[,columns] <- df.mean[,columns] - colMeans(df.mean[,columns])
  if (rounding > -1) {
    df.mean[,columns] <- round(df.mean[,columns], rounding)
  }
  return(df.mean)
}
scatter(centralize(data_transf, columns=c(2:16)), centralize(gt, columns=c(2:6)), default_scaling = FALSE)
```

```{r}
find_transformation <- function(df, column, transformation) {
  density_df <- density(df[,column])
  transformed_df <- data.frame(transformation(df[,column]))
  normalized_df <- transformed_df %>% mutate_at(1, funs((.-min(.))/max(.-min(.))))
  density_transformed <- density(normalized_df[,1])
  maximum <- max(max(densityfull[['y']]),max(densityagree[['y']]))
  plot(density_df, main=paste('Density plot',column), col=color$c1, ylim=c(0,maximum))
  lines(density_transformed, col=color$c2)
  legend(x="topright", y=0.92, legend=c('normal', 'transformed'), col=c(color$c1,color$c2), pch=rep('-',2), lwd=10)
}
find_transformation(data, 16, function(x) sqrt(x + 0.1))
```
