---
title: "Research Question 3 - below 100"
author: "Frenk C.J. van Mil"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r, result='hide', echo=FALSE, include=FALSE}
source('statistics.R')
knitr::opts_chunk$set(comment = NA)
knitr::opts_chunk$set(results = 'asis')
```

### Read in data
```{r, results='hide', echo=FALSE, include=FALSE}
transformations <- list(
  c(13, log10_transform)
)
db_normal <- read_single_db('selected_dev_parsed', transformations = transformations)
db_100 <- read_single_db('selected_dev_parsed_below100', transformations = transformations, where="liwc_filled_golbeck=1")
people_with_100 <- read_single_db('selected_dev_parsed_below100', transformations = transformations, where="word_count<100")

db_normal <- db_normal[,c(1,7:16)]
db_100 <- db_100[,c(1,7:16)]
people_with_100 <- people_with_100[people_with_100$id %in% db_100$id,]
people_with_100[,c(2:11)] <- db_100[db_100$id %in% people_with_100$id,][,c(2:11)]

gt <- get_ground_truth()
gt <- gt[order(gt$id),]

row.names(db_normal) <- NULL
row.names(db_100) <- NULL
row.names(people_with_100) <- NULL
row.names(gt) <- NULL

dfs <- list(db_normal, db_100)
dfnames=list('[normal]','<100]')
```

```{r}
measure_plot(dfs=dfs, dfnames=dfnames, gt=gt, func=RMSE, main="")
measure_plot(dfs=dfs, dfnames=dfnames, gt=gt, func=MAE, main="")
```
