---
title: "Research Question 4"
author: "Frenk C.J. van Mil"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r, result='hide', echo=FALSE, include=FALSE}
source('statistics.R')
```

### Read the data
```{r, results='hide', echo=FALSE, include=FALSE}
transformations <- list(
  c(13, log10_transform)
)
# Read the database values
data_normal <- read_single_db(dbname='selected_dev_parsed', normalize=TRUE, transformations=list(), raw=TRUE)
data_sentiment <- read_single_db(dbname='selected_dev_parsed_sentiment', normalize=TRUE, transformations=list(), raw=TRUE)

dfs=list(data_normal, data_sentiment)
dfnames=c('normal', 'sentiment')

rm(dbs_res1)
```

# Ground-truth inspection
```{r}
gt <- get_ground_truth()
traits = c('Openness', 'Conscientiousness', 'Extraversion', 'Agreeableness', 'Neuroticism')
```

```{r}
# Check the RMSE on each personality trait.
measure_plot(dfs=dfs, dfnames=dfnames, gt=gt, func=RMSE)
```
```{r}
data_normal$golbeck_openness
```

```{r}
max(AE(data_normal, data_sentiment)$golbeck_openness)
```

